apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-controller
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: eventbus-controller
          image: alvarogg777/eventbus-controller:v1.3.1
          env:
            - name: NATS_METRICS_EXPORTER_IMAGE
              value: alvarogg777/prometheus-nats-exporter:0.6.2
     
